# MoWAKi App - development containers
#
# Exposed ports:
# - 8000 - Fontend
# - 8001 - Backend API
# - 8025 - MailSlurper SMTP
# - 8026 - MailSlurper UI
---
include:
  - ./api/compose.yml
  - ./web/compose.yml

services:

  api:
    ports:  # host:container
      - "8001:8100"
    environment:
      PORT: "8100"
      FRONTEND_URL: "http://localhost:8000"
      CORS_ALLOW_ORIGINS: ""

  db:
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: "not-a-secure-password"

  web:
    ports:
      - "8000:8000"
    environment:
      APP_PORT: "8000"
      VITE_API_URL: "http://localhost:8001"

  mailslurper:
    image: oryd/mailslurper:smtps-latest
    ports:
      - "8025:8025"  # www
      - "8026:8026"  # service
      - "8027:8027"  # smtp
    volumes:
      - type: bind
        source: ./etc/mailslurper.json
        target: >-
          /go/src/github.com/mailslurper/mailslurper/cmd/mailslurper/config.json
