version: '3.3'
services:

  database:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'default'
    volumes:
      - db-pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:4
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  db-pgdata:
