[build]
    base    = "web"
    publish = "web/build"
    command = "npm run-script build"

[build.environment]
    API_URL = "https://api.example.com/graphql"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
