---
services:

  # ==================================================================
  # RESTful API service
  # ==================================================================
  api:
    # Build the image from the Dockerfile in the current directory
    build: .

    # Host the FastAPI application on port 8000
    # ports:
    #   - "8000:8000"

    environment:
      # Tool configuration
      UV_NO_DEV: "0"  # Include development dependencies when working locally

      # App configuration
      DATABASE_URL: "postgresql://postgres:not-a-secret@db/default"
      REDIS_URL: ""
      FRONTEND_URL: "http://localhost:8000"
      CORS_ALLOW_ORIGINS: "http://localhost:8000"

      # Testing configuration
      TESTING_ADMIN_DATABASE_URL: >-
        postgresql://postgres:not-a-secret@db/default

    # Run as root during development so the environment is mutable
    # Alternatively, you could set `UV_PROJECT_ENVIRONMENT` to a path
    # owned by the non-root user
    user: root

    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment - it could be for
          # a different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

    depends_on:
      db:
        condition: service_healthy


  # ==================================================================
  # PostgreSQL database
  # ==================================================================
  db:
    image: postgres:18-trixie
    # restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: "default"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "not-a-secret"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
