[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "click>=8.4.1",
    "email-validator>=2.3.0",
    "fastapi[standard]>=0.136.1",
    "publicsuffixlist>=1.0.2.20260615",
    "pydantic-settings>=2.14.1",
    "sqlalchemy[asyncio]>=2.0.50",
    "webauthn>=2.8.0",
]

[dependency-groups]
dev = [
    "ipython>=9.14.1",
    "pdbpp>=0.12.1",
    "pytest>=9.0.3",
    "pytest-annotated>=0.1.1",
    "pytest-asyncio>=1.4.0",
]
